# this is based on https://github.com/irongut/MauiBeach/blob/master/.github/workflows/ci-build.yml
# this might be useful, too:
# https://github.com/dotnet/maui-samples/blob/main/8.0/Apps/WeatherTwentyOne/devops/GitHubActions/

name: CI Build

on:
  pull_request:
    branches:
      - main
  #   push:
  #     # this will trigger a build on any tag push - you can optionally specify a tag format here
  #     tags:
  #       - "*"
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true # Disable sending .NET CLI telemetry

jobs:
  # Check if it even builds
  sanity-check-build:
    runs-on: macos-13
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 15.1
        run: sudo xcode-select -s /Applications/Xcode_15.1.app

      - name: Setup .NET according to global.json
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: Install MAUI Workload
        run: dotnet workload install maui

      - name: Build package
        run: dotnet pack -c Debug src/The49.Maui.BottomSheet.csproj /p:VersionSuffix="-pr-${{ github.event.number }}"

      - name: Upload iOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bottomsheet-ios-ci-build
          path: src/bin/Debug/The49.Maui.BottomSheet.*.nupkg
